statement = substatement (parameter substatement)*

substatement = (( #"[^?:']+" | "::" ) | comment | string)*

comment = (whitespace? COMMENT_MARKER whitespace? (non-whitespace whitespace*)* newline)
COMMENT_MARKER = "--"

string = string-delimiter string-normal* (string-special string-normal*)* string-delimiter
string-delimiter = "'"
string-normal = #"[^'\\]*"
string-special = "\\" #"."

parameter = placeholder-parameter | named-parameter

placeholder-parameter = "?"

named-parameter = <":"> #"[^\s,\"':&;()|=+\-*%/\\<>^]+"

newline = '\n' | '\r\n'
non-whitespace = #'\S+'
whitespace = (' ' | '\t')+
